export const destinations = [
  {
    id: 1,
    name: "Ciudad Amurallada",
    location: "Centro Histórico, Cartagena",
    country: "Colombia",
    category: "Historia",
    rating: 4.9,
    ratingLabel: "4.9 estrellas",
    lat: 10.4236,
    lng: -75.5510,
    description: "Declarada Patrimonio de la Humanidad por la UNESCO en 1984. Sus calles adoquinadas, balcones floridos y coloridas casas coloniales del siglo XVI la convierten en el corazón histórico de Colombia.",
    longDescription: "La Ciudad Amurallada de Cartagena de Indias es una de las joyas del patrimonio mundial. Construida entre los siglos XVI y XVII para proteger el puerto más importante del Caribe, sus murallas se extienden por más de 13 km. Al recorrerla encontrarás la Torre del Reloj, el Palacio de la Inquisición, la Plaza de Bolívar, iglesias coloniales y una arquitectura que ha sobrevivido intacta por más de 400 años.",
    tags: ["Historia", "Patrimonio UNESCO", "Colonial"],
    price: 150000,
    priceLabel: "150.000 COP",
    image: "/img/Ciudadamurallada/1.jpg",
    images: [
      "/img/Ciudadamurallada/2.jpg",
      "/img/Ciudadamurallada/3.jpg",
      "/img/Ciudadamurallada/4.jpg",
      "/img/Ciudadamurallada/5.jpg",
      "/img/Ciudadamurallada/6.jpg",
    ],
    restaurants: [
      { name: "Celele", type: "Alta cocina caribeña", rating: 4.9, price: "$$$", description: "Referente de la gastronomía del Caribe colombiano en Getsemaní." },
      { name: "Carmen", type: "Cocina contemporánea colombiana", rating: 4.8, price: "$$$$", description: "Menú degustación de 7 tiempos que celebra la biodiversidad colombiana." },
      { name: "La Cocina de Pepina", type: "Caribeña tradicional", rating: 4.7, price: "$$", description: "Auténtica cocina cartagenera. Famosa por el mote de queso y el sancocho de pescado." },
    ],
    features: [
      { label: "Fundación", value: "1533 por Pedro de Heredia" },
      { label: "Patrimonio", value: "UNESCO desde 1984" },
      { label: "Temperatura", value: "28–31°C todo el año" },
      { label: "Mejor época", value: "Diciembre – Abril" },
      { label: "Moneda", value: "Peso Colombiano (COP)" },
      { label: "Tiempo recomendado", value: "2–3 días" },
    ],
  },
  {
    id: 2,
    name: "Castillo de San Felipe de Barajas",
    location: "Pie del Cerro San Lázaro, Cartagena",
    country: "Colombia",
    category: "Historia",
    rating: 4.8,
    ratingLabel: "4.8 estrellas",
    lat: 10.4211,
    lng: -75.5394,
    description: "La fortaleza militar más grande construida por los españoles en América. Patrimonio de la Humanidad UNESCO y una de las 7 maravillas de Colombia.",
    longDescription: "Construido sobre el cerro de San Lázaro en 1657, el Castillo de San Felipe de Barajas es una obra maestra de la ingeniería militar española. Sus túneles subterráneos, cañones originales, galerías y baluartes te transportan a la época colonial. Desde su cima tendrás unas vistas impresionantes de la bahía de Cartagena y toda la ciudad.",
    tags: ["Historia", "Arquitectura", "Militar"],
    price: 35000,
    priceLabel: "35.000 COP",
    image: "/img/Castillodesanfelipe/1.jpg",
    images: [
      "/img/CastilloDeSanFelipe/2.jpg",
      "/img/CastilloDeSanFelipe/3.jpg",
      "/img/CastilloDeSanFelipe/4.jpg",
      "/img/CastilloDeSanFelipe/5.jpg",
      "/img/CastilloDeSanFelipe/6.jpg",
    ],
    restaurants: [
      { name: "El Santísimo", type: "Colombiana / Caribeña", rating: 4.7, price: "$$$", description: "A pasos del castillo, cocina colombiana contemporánea en un patio colonial." },
      { name: "Alma", type: "Mediterránea / Colombiana", rating: 4.6, price: "$$$", description: "Brunch y almuerzos con productos locales de primera calidad." },
      { name: "Candé", type: "Herencia cartagenera", rating: 4.8, price: "$$$", description: "Ganador del premio Mejor Restaurante Nacional 2021. Cocina 100% cartagenera." },
    ],
    features: [
      { label: "Construcción", value: "1657 – Siglo XVII" },
      { label: "Patrimonio", value: "UNESCO desde 1984" },
      { label: "Entrada", value: "35.000 COP adultos" },
      { label: "Horario", value: "8:00 AM – 6:00 PM" },
      { label: "Altitud", value: "40 metros s.n.m." },
      { label: "Tiempo recomendado", value: "2–3 horas" },
    ],
  },
  {
    id: 3,
    name: "Islas del Rosario",
    location: "Archipiélago del Rosario, Cartagena",
    country: "Colombia",
    category: "Playa",
    rating: 4.9,
    ratingLabel: "4.9 estrellas",
    lat: 10.1758,
    lng: -75.7697,
    description: "Paraíso caribeño de aguas cristalinas turquesas y arrecifes de coral a 1 hora en lancha de Cartagena. Parque Nacional Natural Corales del Rosario.",
    longDescription: "El archipiélago de las Islas del Rosario está conformado por 27 islas e islotes coralinos en el Mar Caribe. Sus aguas son perfectas para snorkel, buceo, kayak y observación de vida marina. La isla principal, Isla Grande, tiene manglares, senderos y restaurantes de mariscos frescos.",
    tags: ["Playa", "Snorkel", "Naturaleza"],
    price: 120000,
    priceLabel: "120.000 COP",
    image: "/img/IslaDelRosario/1.jpg",
    images: [
      "/img/IslaDelRosario/2.jpg",
      "/img/IslaDelRosario/3.jpg",
      "/img/IslaDelRosario/4.jpg",
      "/img/IslaDelRosario/5.jpg",
      "/img/IslaDelRosario/6.jpg",
    ],
    restaurants: [
      { name: "El Restaurante de Isla Grande", type: "Mariscos frescos", rating: 4.7, price: "$$", description: "Mariscos capturados el mismo día, arroz de coco y patacones frente al mar." },
      { name: "La Cholita", type: "Caribeña / Pescados", rating: 4.5, price: "$$", description: "Cocina isleña tradicional con langosta, pargo y camarones a la plancha." },
      { name: "Decamerón Isla", type: "Buffet / Internacional", rating: 4.3, price: "$$$", description: "Restaurante resort con buffet de mariscos y cocina internacional en Isla Barú." },
    ],
    features: [
      { label: "Acceso", value: "Lancha desde Muelle La Bodeguita" },
      { label: "Duración viaje", value: "1–1.5 horas en lancha" },
      { label: "Temperatura del agua", value: "26–29°C" },
      { label: "Mejor época", value: "Diciembre – Abril" },
      { label: "Actividades", value: "Snorkel, buceo, kayak" },
      { label: "Tiempo recomendado", value: "1–2 días" },
    ],
  },
  {
    id: 4,
    name: "Barrio Getsemaní",
    location: "Getsemaní, Cartagena",
    country: "Colombia",
    category: "Cultura",
    rating: 4.7,
    ratingLabel: "4.7 estrellas",
    lat: 10.4197,
    lng: -75.5546,
    description: "El barrio más auténtico y bohemio de Cartagena. Arte urbano, murales coloridos, vida nocturna vibrante y la Plaza de la Trinidad.",
    longDescription: "Getsemaní fue el arrabal de los trabajadores portuarios en la época colonial. Hoy es el barrio más cool de Cartagena, lleno de murales gigantes, galerías de arte, restaurantes con sazón local y bares animados. La Plaza de la Trinidad es el punto de encuentro al atardecer.",
    tags: ["Arte", "Cultura", "Bohemio"],
    price: 0,
    priceLabel: "Entrada libre",
    image: "/img/Getsemaní/1.jpg",
    images: [
      "/img/Getsemaní/2.jpg",
      "/img/Getsemaní/3.jpg",
      "/img/Getsemaní/4.jpg",
      "/img/Getsemaní/5.jpg",
      "/img/Getsemaní/6.jpg",
    ],
    restaurants: [
      { name: "Celele", type: "Alta cocina caribeña", rating: 4.9, price: "$$$", description: "El mejor restaurante de Cartagena. En la Calle del Espíritu Santo." },
      { name: "La Cevichería", type: "Mariscos / Ceviche", rating: 4.8, price: "$$", description: "El ceviche más famoso de Cartagena. Recomendado por Anthony Bourdain." },
      { name: "Esquina Cocktail Bar", type: "Cócteles / Tapas", rating: 4.7, price: "$$", description: "Cócteles tropicales con frutas naturales en la Plaza de la Trinidad." },
    ],
    features: [
      { label: "Tipo", value: "Barrio histórico y bohemio" },
      { label: "Ambiente", value: "Arte urbano y vida nocturna" },
      { label: "Temperatura", value: "28–31°C" },
      { label: "Mejor hora", value: "Atardecer y noche" },
      { label: "Acceso", value: "A pie desde la Ciudad Amurallada" },
      { label: "Tiempo recomendado", value: "Medio día + noche" },
    ],
  },
  {
    id: 5,
    name: "Playa Blanca – Isla Barú",
    location: "Isla Barú, Cartagena",
    country: "Colombia",
    category: "Playa",
    rating: 4.8,
    ratingLabel: "4.8 estrellas",
    lat: 10.2108,
    lng: -75.6358,
    description: "Una de las playas más hermosas de Colombia. Arena blanca como talco, palmeras y aguas turquesas del Caribe a 45 minutos de Cartagena.",
    longDescription: "Playa Blanca en la Isla Barú es uno de los paraísos del Caribe colombiano. Su arena es fina y blanca como talco, sus aguas son cálidas y turquesas. Puedes llegar en lancha o en bus. El ambiente es relajado, con mujeres palenqueras vendiendo frutas y cocadas en la orilla.",
    tags: ["Playa", "Caribe", "Naturaleza"],
    price: 80000,
    priceLabel: "80.000 COP",
    image: "/img/PlayaBlanca/1.jpg",
    images: [
      "/img/PlayaBlanca/2.jpg",
      "/img/PlayaBlanca/3.jpg",
      "/img/PlayaBlanca/4.jpg",
      "/img/PlayaBlanca/5.jpg",
    ],
    restaurants: [
      { name: "Restaurante La Sirena", type: "Mariscos a la orilla del mar", rating: 4.5, price: "$$", description: "Pescado fresco, langosta y camarones con los pies en la arena." },
      { name: "El Pelícano", type: "Caribeña / Mariscos", rating: 4.4, price: "$$", description: "Arroz de coco, pargo rojo a la plancha y cocadas de mujeres palenqueras." },
      { name: "Rancho de La Playa", type: "Criolla costeña", rating: 4.3, price: "$", description: "Sancocho de pescado, mazamorra y jugos de frutas tropicales recién cortadas." },
    ],
    features: [
      { label: "Acceso", value: "Lancha o bus desde Cartagena" },
      { label: "Duración viaje", value: "45 min – 1.5 horas" },
      { label: "Temperatura del agua", value: "27–30°C" },
      { label: "Mejor época", value: "Diciembre – Abril" },
      { label: "Tipo de arena", value: "Arena blanca muy fina" },
      { label: "Tiempo recomendado", value: "1 día completo" },
    ],
  },
  {
    id: 6,
    name: "Convento de La Popa",
    location: "Cerro de La Popa, Cartagena",
    country: "Colombia",
    category: "Historia",
    rating: 4.7,
    ratingLabel: "4.7 estrellas",
    lat: 10.4356,
    lng: -75.5375,
    description: "El punto más alto de Cartagena a 150 metros. Convento del siglo XVII con vistas panorámicas 360° de la ciudad, la bahía y el Mar Caribe.",
    longDescription: "El Convento de Nuestra Señora de la Candelaria fue fundado en 1607 por los frailes agustinos. Es el primer monumento que los barcos divisaban al llegar a Cartagena. Desde su mirador tendrás la vista más espectacular de toda la ciudad.",
    tags: ["Historia", "Religión", "Miradores"],
    price: 18000,
    priceLabel: "18.000 COP",
    image: "/img/ConventoDeLaPopa/1.jpg",
    images: [
      "/img/ConventoDeLaPopa/2.jpg",
      "/img/ConventoDeLaPopa/3.jpg",
      "/img/ConventoDeLaPopa/4.jpg",
      "/img/ConventoDeLaPopa/5.jpg",
    ],
    restaurants: [
      { name: "El Bistro", type: "Colombiana / Internacional", rating: 4.5, price: "$$", description: "Con terraza y vistas a la ciudad amurallada. Brunch y almuerzos con ingredientes locales." },
      { name: "Donde Francesca", type: "Italiana / Mediterránea", rating: 4.8, price: "$$$", description: "Uno de los más recomendados de Cartagena. Cocina italiana con toque caribeño." },
      { name: "Harry Sasson Cartagena", type: "Cocina colombiana de autor", rating: 4.9, price: "$$$$", description: "Del chef más famoso de Colombia. Arepas de huevo doradas y posta negra." },
    ],
    features: [
      { label: "Altitud", value: "150 metros s.n.m." },
      { label: "Fundación", value: "1607 – Frailes agustinos" },
      { label: "Entrada", value: "18.000 COP adultos" },
      { label: "Horario", value: "8:30 AM – 5:30 PM" },
      { label: "Vistas", value: "Panorámica 360° de la ciudad" },
      { label: "Tiempo recomendado", value: "1.5–2 horas" },
    ],
  },
  {
    id: 7,
    name: "Museo del Oro Zenú",
    location: "Plaza Bolívar, Centro Histórico, Cartagena",
    country: "Colombia",
    category: "Museos",
    rating: 4.6,
    ratingLabel: "4.6 estrellas",
    lat: 10.4244,
    lng: -75.5509,
    description: "Colección de objetos en oro y cerámica de la cultura Zenú, una de las civilizaciones prehispánicas más importantes del Caribe. Entrada gratuita.",
    longDescription: "El Museo del Oro Zenú del Banco de la República exhibe una fascinante colección de piezas de orfebrería, cerámica y tejidos de la cultura Zenú. La colección muestra la sofisticación de esta civilización en metalurgia, hidráulica y agricultura hace más de 2.000 años.",
    tags: ["Museos", "Cultura", "Gratuito"],
    price: 0,
    priceLabel: "Entrada gratuita",
    image: "/img/MuseodelOro/1.jpg",
    images: [
      "/img/MuseodelOro/2.jpg",
      "/img/MuseodelOro/3.jpg",
      "/img/MuseodelOro/4.jpg",
    ],
    restaurants: [
      { name: "Juan Valdez Café – Plaza Bolívar", type: "Café colombiano", rating: 4.5, price: "$", description: "El mejor café colombiano con vista a la Plaza Bolívar y la ciudad amurallada." },
      { name: "El Portal de los Dulces", type: "Dulces típicos", rating: 4.3, price: "$", description: "Tradicional portal con cocadas, alegrías y dulces artesanales de Cartagena." },
      { name: "Mary Zielo", type: "Cocina colombiana de autor", rating: 4.8, price: "$$$$", description: "En Casa La Escribana, cocina inspirada en recetas de matronas colombianas." },
    ],
    features: [
      { label: "Entrada", value: "Gratuita" },
      { label: "Horario", value: "Martes a Sábado 9AM–5PM" },
      { label: "Colección", value: "Cultura Zenú, 200 a.C." },
      { label: "Ubicación", value: "Plaza Bolívar, Ciudad Amurallada" },
      { label: "Duración visita", value: "1–2 horas" },
      { label: "Temperatura", value: "Aire acondicionado" },
    ],
  },
  {
    id: 8,
    name: "Bocagrande",
    location: "Bocagrande, Cartagena",
    country: "Colombia",
    category: "Playa",
    rating: 4.4,
    ratingLabel: "4.4 estrellas",
    lat: 10.3953,
    lng: -75.5548,
    description: "El sector turístico moderno de Cartagena con playas urbanas, hoteles de lujo, restaurantes y centros comerciales frente al Caribe.",
    longDescription: "Bocagrande es la zona más moderna y turística de Cartagena. Sus playas son accesibles y concurridas. La avenida principal está llena de hoteles internacionales, centros comerciales, restaurantes de todo tipo y vida nocturna vibrante.",
    tags: ["Playa", "Moderno", "Hoteles"],
    price: 0,
    priceLabel: "Acceso libre",
    image: "/img/BocagrandePlaya/1.jpg",
    images: [
      "/img/BocagrandePlaya/2.jpg",
      "/img/BocagrandePlaya/3.jpg",
      "/img/BocagrandePlaya/4.jpg",
      "/img/BocagrandePlaya/5.jpg",
      "/img/BocagrandePlaya/6.jpg",
    ],
    restaurants: [
      { name: "La Cevichería", type: "Mariscos / Ceviche", rating: 4.8, price: "$$", description: "El ceviche más famoso de Cartagena, recomendado por Anthony Bourdain." },
      { name: "Di Silvio Trattoria", type: "Italiana", rating: 4.5, price: "$$", description: "Auténtica cocina italiana en Bocagrande, perfecta para una cena romántica." },
      { name: "El Coroncoro", type: "Cartagenera tradicional", rating: 4.4, price: "$", description: "Platos típicos a precios locales. Sancocho, arroz de coco y pargo a la plancha." },
    ],
    features: [
      { label: "Tipo", value: "Zona turística moderna" },
      { label: "Playa", value: "Pública, concurrida" },
      { label: "Temperatura", value: "28–32°C" },
      { label: "Mejor época", value: "Todo el año" },
      { label: "Transporte", value: "Taxi desde el centro 10–15 min" },
      { label: "Ambiente", value: "Familiar y turístico" },
    ],
  },
  {
    id: 9,
    name: "Palacio de la Inquisición",
    location: "Plaza Bolívar, Centro Histórico, Cartagena",
    country: "Colombia",
    category: "Museos",
    rating: 4.6,
    ratingLabel: "4.6 estrellas",
    lat: 10.4241,
    lng: -75.5513,
    description: "Sede del Tribunal de la Santa Inquisición durante más de 200 años. Hoy museo histórico con instrumentos de tortura y documentos originales del siglo XVI.",
    longDescription: "El Palacio de la Inquisición es uno de los mejores ejemplos de arquitectura colonial barroca de América. Fue sede del temido Tribunal del Santo Oficio que juzgó a más de 800 personas. Hoy alberga el Museo Histórico de Cartagena con exposiciones fascinantes sobre la historia colonial.",
    tags: ["Historia", "Museos", "Colonial"],
    price: 25000,
    priceLabel: "25.000 COP",
    image: "/img/PalaciodelaInquisicion/1.jpg",
    images: [
      "/img/PalaciodelaInquisicion/2.jpg",
      "/img/PalaciodelaInquisicion/3.jpg",
      "/img/PalaciodelaInquisicion/4.jpg",
      "/img/PalaciodelaInquisicion/5.jpg",
    ],
    restaurants: [
      { name: "Juan Valdez – Torre del Reloj", type: "Café colombiano", rating: 4.6, price: "$", description: "Terraza con vistas a la Plaza de los Coches y la Torre del Reloj." },
      { name: "La Mulata", type: "Caribeña / Criolla", rating: 4.7, price: "$$", description: "Cocina costeña auténtica con vista al centro histórico. Bandejas y mote de queso." },
      { name: "El Bololó", type: "Criolla económica", rating: 4.3, price: "$", description: "Platos del día por 15.000 COP. El mejor para comer bien y barato en el centro." },
    ],
    features: [
      { label: "Construcción", value: "1706 – 1770" },
      { label: "Entrada", value: "25.000 COP adultos" },
      { label: "Horario", value: "Lun–Sáb 9AM–5PM / Dom 10AM–4PM" },
      { label: "Estilo", value: "Arquitectura barroca colonial" },
      { label: "Ubicación", value: "Plaza Bolívar" },
      { label: "Tiempo recomendado", value: "1.5–2 horas" },
    ],
  },
  {
    id: 10,
    name: "Tour Atardecer en Bahía",
    location: "Muelle de los Pegasos, Cartagena",
    country: "Colombia",
    category: "Aventura",
    rating: 4.9,
    ratingLabel: "4.9 estrellas",
    lat: 10.4268,
    lng: -75.5491,
    description: "Navega por la bahía de Cartagena al atardecer en velero, catamarán o el famoso Galeón Pirata. Una experiencia mágica con el Caribe de fondo.",
    longDescription: "El atardecer en la bahía de Cartagena es una de las experiencias más mágicas del Caribe. Desde el Muelle de los Pegasos parten cada tarde veleros, catamaranes y el famoso Galeón Phantom con música en vivo y bebidas. Ver las murallas iluminadas desde el mar es una experiencia inolvidable.",
    tags: ["Aventura", "Romántico"],
    price: 90000,
    priceLabel: "90.000 COP",

    // 👇 IMAGEN PRINCIPAL
    image: "/img/Atardecerenlabahía/1.jpg",

    // 👇 GALERÍA
    images: [
      "/img/Atardecerenlabahía/1.jpg",
      "/img/Atardecerenlabahía/2.avif",
      "/img/Atardecerenlabahía/3.jpg",
      "/img/Atardecerenlabahía/4.jpg",
      "/img/Atardecerenlabahía/5.jpg",
    ],

    restaurants: [
      { name: "Restaurante en el Galeón Phantom", type: "Cena a bordo", rating: 4.8, price: "$$$", description: "Cena romántica navegando por la bahía con música en vivo y mariscos frescos." },
      { name: "Club de Pesca", type: "Mariscos / Vista a la bahía", rating: 4.7, price: "$$$", description: "El restaurante más clásico frente a la bahía. Desde 1938." },
      { name: "La Vitrola", type: "Colombiana / Caribeña", rating: 4.8, price: "$$$", description: "Música vallenata en vivo y cocina cartagenera en la ciudad amurallada." },
    ],

    features: [
      { label: "Salida", value: "Muelle de los Pegasos, 5PM" },
      { label: "Duración", value: "2–3 horas" },
      { label: "Opciones", value: "Velero, catamarán, galeón" },
      { label: "Incluye", value: "Bebidas y aperitivos" },
      { label: "Mejor época", value: "Todo el año" },
      { label: "Ideal para", value: "Parejas y grupos" },
    ],
  },
];
